name: Week 12 Dockerized Application

on:
  push:
    branches:
      - main  # Run workflow when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for building and pushing images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/health-reminder-app:latest

      # Step 5: Verify the container runs successfully (optional)
      - name: Run container for testing
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/health-reminder-app:latest
          sleep 10
          curl http://localhost:5000
